
/**
 * @fileOverview Stores teleprompter scripts mapped to prompt IDs.
 */

export const teleprompterScripts: Record<string, string> = {
  p1_1: `Let's start right at the beginning. Could you share some details about your birthplace – perhaps a specific memory of that place that stands out?`,
  p1_2: `And tell us about your family roots; were there any particular traditions, stories, or values passed down through generations that significantly influenced you?`,
  p1_3: `How did the cultural environment you grew up in—whether it was a blend of different cultures or a very specific one—shape your early perspectives and who you are today?`,
  p1_4: `Were there specific customs, foods, or languages that were central to your upbringing?`,
  p1_5: `And thinking about your parents or primary caregivers, what were some of their core values or beliefs that they instilled in you from a young age?`,
  p1_6: `How did those foundational elements contribute to your initial understanding of the world?`,
  p2_1: `Now, let's turn our attention to the house itself. What was daily life like within those walls? Describe the atmosphere, the routines, the sounds, and even the smells that you remember most vividly.`,
  p2_2: `What were the different rooms like, and what significant moments happened in them?`,
  p2_3: `Thinking back to your very first memories, what specific scenes or feelings come to mind when you recall your childhood home?`,
  p2_4: `Were there particular chores, family meals, or weekend activities that stand out in your memory?`,
  p2_5: `And how did that physical environment, the very structure and feeling of your home, shape your sense of comfort, security, or even your earliest adventures and curiosities?`,
  p3_1: `Moving into your early years, let's talk about your school days. What subjects captivated you, or perhaps challenged you the most, and why?`,
  p3_2: `Were there any teachers who left a lasting impression on you, and if so, how did they influence your thinking or your path?`,
  p3_3: `Beyond academics, what were your early dreams and aspirations as a child? Did you imagine yourself doing something extraordinary, or were your dreams simpler and more immediate?`,
  p3_4: `What moments from your childhood truly filled you with a sense of wonder or insatiable curiosity? This could be anything from discovering a new book, exploring a natural space, or learning something profound for the first time.`,
  p3_5: `What ignited that spark of curiosity in you back then, and how did it guide your early explorations?`,
  p4_1: `Our relationships often shape us profoundly. Thinking about your early life, who were some of the key individuals—perhaps siblings, close friends, or even early mentors—who made a significant impact on you?`,
  p4_2: `Can you recall specific memories or interactions with them that stand out? What qualities did you admire in these people?`,
  p4_3: `What lessons did they teach you, either directly through their advice or indirectly through their actions and character?`,
  p4_4: `How did these early relationships influence your understanding of concepts like friendship, loyalty, conflict resolution, or even love?`,
  p4_5: `What kind of 'echoes' do their personalities or shared experiences still resonate with in your life today?`,
  p5_1: `Life also presents us with difficulties, even in our early years. Can you describe your first encounters with grief or significant challenges during your youth, such as the loss of a loved one, a beloved pet, or perhaps a significant disappointment, failure, or even a deep fear.`,
  p5_2: `How did you process these early experiences with loss? What emotions did you feel, and who, if anyone, offered you support or comfort during those times?`,
  p5_3: `How did these early encounters with hardship—the 'shape of loss,' as it were—begin to inform your understanding of resilience, vulnerability, or the impermanence of things?`,
  p5_4: `What did you learn about yourself or the world during those difficult moments that stayed with you?`,
  p6_1: `Transitioning into adolescence, a time often marked by significant change and self-discovery, what were some of the 'crossroads and choices' you encountered?`,
  p6_2: `How did you begin to form your own identity, separate from your family's or peers' expectations?`,
  p6_3: `Can you recall any specific dilemmas or pivotal decisions you faced during these formative years? This could relate to friendships, academic paths, personal values, career aspirations, or even early romantic interests.`,
  p6_4: `What pressures did you feel, both internal and external, and how did you navigate them?`,
  p6_5: `What did you learn about making independent choices, especially when they felt daunting or had significant implications for your future?`,
  p7_1: `We all learn through experience, and sometimes, the most profound lessons come from challenging ones. Can you share a specific instance where you feel you 'learned the hard way'?`,
  p7_2: `What was the mistake, setback, or challenge, and what were the immediate consequences you faced?`,
  p7_3: `How did that experience impact your self-perception, your confidence, or your path forward?`,
  p7_4: `And perhaps more importantly, were there any specific mentors, teachers, friends, or even books or philosophies that offered you guidance or a new perspective during these times of self-discovery?`,
  p7_5: `How did their wisdom or your own reflections help you understand yourself better and truly grow from those difficult experiences?`,
  p8_1: `Our lives are often defined by the journeys we take, both physically and intellectually. Could you describe any significant travels you undertook in your younger years, and how exploring new places, cultures, or different ways of life broadened your perspective?`,
  p8_2: `How did your formal education or any informal learning experiences outside the classroom shape your worldview, your skills, and your passions?`,
  p8_3: `And beyond travel and education, what pivotal personal experiences—moments of profound insight, unexpected challenge, or deep personal transformation—played a crucial role in shaping the person you are today?`,
  p8_4: `How did these 'journeys within and without' expand your horizons and refine your understanding of yourself and the world?`,
  p9_1: `As you transitioned into full adulthood, what was that experience like for you? How did it feel to 'face reality' and begin carving out your own unique place in the world, distinct from your upbringing?`,
  p9_2: `What were some of the initial challenges or excitements of becoming truly independent, managing your own life, and making your own way?`,
  p9_3: `How did your goals and priorities shift during this period as you took on new responsibilities?`,
  p9_4: `What did you learn about responsibility, self-sufficiency, and navigating the complexities of adult life?`,
  p9_5: `Were there particular moments when you felt a distinct shift from adolescence to a more mature sense of self, and what did that feel like to truly 'become'?`,
  p10_1: `Now, let's move into a very rich chapter of life. Can you tell us about your experiences with love, whether it's romantic love, deep friendships, or a general 'falling in love with life' in a broader, more existential sense?`,
  p10_2: `For those who experienced it, how did marriage or a significant partnership transform your life and your understanding of commitment and companionship?`,
  p10_3: `What about parenthood? How did embracing these roles—love, partnership, and potentially raising a family—deepen your understanding of connection, profound commitment, and the human experience itself?`,
  p10_4: `What were some of the most profound joys and perhaps unexpected challenges of these significant relationships?`,
  p11_1: `For those who became parents, let's delve deeper into 'the birth of children.' What was it like experiencing the arrival of your child or children?`,
  p11_2: `Can you describe the immediate feelings, the overwhelming emotions, and the profound transformation you underwent as you stepped into the role of a parent?`,
  p11_3: `How did your priorities shift, and what unexpected joys or difficulties did you encounter in those early days and years of parenthood?`,
  p11_4: `What fundamental lessons about life, unconditional love, and sacrifice did you learn through the unique and ongoing experience of raising your children?`,
  p11_5: `How did becoming a parent redefine your sense of purpose and your perspective on the future?`,
  p12_1: `Life often presents us with trials that test our limits. Can you reflect on periods when you had to navigate significant challenges—perhaps financial difficulties, deep emotional struggles, or even spiritual crises that shook your foundations?`,
  p12_2: `What was it like to 'hold on' during those tough times, to find the inner strength or external support to persevere when things felt overwhelming?`,
  p12_3: `And conversely, what were the moments when you realized the importance of 'letting go'—releasing control, expectations, grievances, or even past hurts?`,
  p12_4: `How did these experiences with life's various challenges shape your resilience and your understanding of what truly matters, and what doesn't?`,
  p13_1: `Building on the idea of challenges, can you recall a specific 'test of fire'—a moment or period of deep struggle that truly pushed you to your absolute limits?`,
  p13_2: `What was the nature of this struggle, and what was it like to be in the very midst of it, feeling the intensity of the pressure?`,
  p13_3: `What resources did you draw upon—whether internal strength, external support from others, or a guiding philosophy—to get through it?`,
  p13_4: `And most importantly, how did you 'rise again' from that experience?`,
  p13_5: `What profound insights did you gain about your own strength, your capacity for healing, or your ability to transform adversity into personal growth?`,
  p13_6: `How did that intense period fundamentally change your trajectory or your perspective on life?`,
  p14_1: `Many people experience a journey of 'faith in the invisible,' whether through formal religion or a more personal spiritual path. Can you share any spiritual awakenings, shifts in belief, or moments where you felt a profound sense of guidance from within or from a higher power, however you define that? This doesn't have to be religious; it could be a deep connection to nature, art, humanity, or a profound sense of purpose.`,
  p14_2: `How have these experiences or beliefs provided comfort, meaning, or direction in your life?`,
  p14_3: `How do you define your personal 'faith,' and how does it influence your daily actions, your worldview, and your understanding of life's bigger questions?`,
  p15_1: `Reflecting on your life's journey, how have your 'wounds transformed into wisdom'?`,
  p15_2: `Can you identify specific instances of pain, past mistakes, or regrets that, over time, have yielded valuable life lessons you carry with you today?`,
  p15_3: `What was the process of healing like for you? How did you navigate those difficult emotions, process the experiences, and ultimately arrive at a place of understanding, acceptance, or even gratitude for the lessons learned?`,
  p15_4: `What unique insights or perspectives do you now hold because of those challenging experiences that you might not have gained otherwise, and how do you apply them now?`,
  p16_1: `If you could write 'letters to those who are watching'—perhaps younger generations, your children, grandchildren, or even your younger self—what essential life advice or key principles would you impart?`,
  p16_2: `What are some core observations or truths you've gathered through your experiences that you feel are crucial to share?`,
  p16_3: `Furthermore, what reflections do you have on the growth and development of others you've mentored, influenced, or simply observed on their own journeys?`,
  p16_4: `What moments of their progress have filled you with pride, and what encouragement or warnings would you offer them as they navigate their own lives and futures?`,
  p17_1: `We all have internal dialogues, or 'conversations with myself.' What are some of your prevailing personal philosophies, core beliefs, or guiding principles that shape your approach to life?`,
  p17_2: `On the flip side, what doubts, recurring questions, or existential ponderings do you grapple with in these internal dialogues?`,
  p17_3: `How does humor play a role in your life, especially when confronting difficulties or self-reflection?`,
  p17_4: `And can you acknowledge any interesting contradictions within your own character or worldview that make you uniquely you?`,
  p17_5: `What do these ongoing internal conversations reveal about the complexities and nuances of your authentic self?`,
  p18_1: `Looking at 'the person in the mirror' today, how would you offer an honest self-assessment of who you are?`,
  p18_2: `What are some of your enduring habits, both positive traits you cherish and perhaps those you're still actively working on?`,
  p18_3: `What brings you the most profound joys, fulfillment, and contentment in your daily life right now?`,
  p18_4: `And conversely, what regrets, if any, do you hold from your past choices or missed opportunities?`,
  p18_5: `How do you reconcile these different facets of your being—your strengths, weaknesses, joys, and regrets—to create a holistic and authentic picture of yourself?`,
  p18_6: `What aspects of your character do you cherish most, and which are still evolving?`,
  p19_1: `Often, the most significant changes or deepest forms of growth occur not in grand achievements, but in 'the quiet victories'—those small, unseen moments that profoundly shape our souls. Can you recall any such instances? These might not be public triumphs, but rather subtle shifts in perspective, moments of quiet resilience in the face of a challenge, or small acts of kindness given or received that had a deep, personal impact on you.`,
  p19_2: `How did these seemingly minor events contribute to your personal growth, redefine your understanding of success and fulfillment, or offer a profound sense of peace?`,
  p19_3: `What is the cumulative effect of these quiet victories on the person you've become?`,
  p20_1: `As we look ahead, what 'still lies ahead' for you?`,
  p20_2: `What dreams, aspirations, or creative projects do you still hope to pursue, whether they are personal, professional, or related to giving back to the world?`,
  p20_3: `What new experiences, knowledge, or connections do you seek in the chapters yet to be written?`,
  p20_4: `And shifting focus to the future beyond yourself, what are your deepest hopes and wishes for the next generation?`,
  p20_5: `What kind of world do you envision for them, and what wisdom, warnings, or encouragement would you offer them as they embark on their own unique journeys?`,
  p21_1: `A classic question that invites deep reflection: 'If I could do it again,' what aspects of your life would you wholeheartedly repeat, reliving those moments of profound joy, significant growth, or deep connection?`,
  p21_2: `And conversely, what, if anything, would you change, given the wisdom of hindsight? This isn't about dwelling on regret, but rather about the valuable lessons gained through time and experience.`,
  p21_3: `What choices or paths might you alter, and why?`,
  p21_4: `How have your perspectives on past decisions evolved over time, and what does that evolution tell you about growth, forgiveness, and acceptance of your own journey?`,
  p22_1: `In what ways do you continue your 'final experiment with truth' in your daily life?`,
  p22_2: `How do you define your core truth and the values that are non-negotiable for you now, after all you've experienced?`,
  p22_3: `Has your spiritual clarity deepened or shifted over time, and what does that mean for your sense of peace and purpose?`,
  p22_4: `What beliefs or understandings serve as your anchor in life's unpredictable storms?`,
  p22_5: `How do you continually seek to align your actions with your deepest convictions, and what does it mean to live authentically and with integrity in your present reality, striving for that ultimate truth?`,
  p23_1: `As we conclude our conversation, how do you see 'the story continuing'?`,
  p23_2: `What hopeful note would you like to leave regarding your legacy—not just in terms of tangible achievements, but in the intangible impact you've had on others, the lessons you've shared, and the love you've given?`,
  p23_3: `How do you envision the ongoing narrative of your family and their future, knowing they carry parts of your story?`,
  p23_4: `And finally, what are your thoughts on the great unknown that still lies ahead, whether it's personal for you or for humanity as a whole?`,
  p23_5: `What sense of optimism, peace, or wonder do you carry forward into the future?`,
  p24_1: `Finally, consider this entire conversation as a 'time travel' exercise for yourself. Why is it important to revisit and reflect on older entries, on these past memories and experiences, perhaps even watching these videos years from now?`,
  p24_2: `What value do you find in looking back, gaining new insights, or simply appreciating how far you've come and the person you've become?`,
  p24_3: `How does the act of reflection contribute to your ongoing understanding of yourself and your life's journey?`,
  p24_4: `What does this continuous process of looking back, integrating, and moving forward reveal about the dynamic and evolving nature of who you are?`,

  // Family Storytelling Prompts
  fs1_1: `Share a cherished memory of a grandparent or elder. What made them special to you?`,
  fs1_2: `What specific moments do you recall that highlight their personality or the impact they had on your life?`,
  fs1_3: `Think about their wisdom, their quirks, or any traditions they passed on.`,
  fs2_1: `What is a family tradition that has been passed down through generations? Describe the tradition in detail.`,
  fs2_2: `When does it happen? Who participates?`,
  fs2_3: `What is its significance to your family, and what emotions or memories does it evoke for you?`,
  fs3_1: `Describe a significant historical event (local, national, or international) that impacted your family.`,
  fs3_2: `How did your family members experience or react to this event?`,
  fs3_3: `What stories have been passed down about it, and how did it shape your family's path or perspectives?`,
  fs4_1: `What values did your parents or guardians instill in you? Think about the core principles they emphasized, whether through words or actions.`,
  fs4_2: `How did they teach these values, and how have these values influenced your own life choices and beliefs?`,
  fs5_1: `Tell a story about an ancestor that you admire. It could be someone you knew personally or someone you only know through family stories.`,
  fs5_2: `What qualities did they possess that you find admirable? What challenges did they overcome, or what legacy did they leave behind?`,
  fs6_1: `Record a message for your children or grandchildren (or future generations) to hear in the future. What wisdom, hopes, or advice would you like to share with them?`,
  fs6_2: `What do you want them to know about you, your life, and the times you lived in? Speak from the heart.`,
};

export const defaultTeleprompterFallbackScript = "Remember to pause and take your time answering, letting your thoughts flow naturally. Good luck with your video or Audio project!";
